### PR TITLE
Add support fo Logitech 3D Pro

### PR DESCRIPTION
**Pull request by stefanahman**

### CODE REVIEW

**Comment by juliancheal** [comment]
Thanks for this PR. It looks great. We just need to see why the tests are failing, then I'm good to merge.

**Comment by stefanahman** [comment]
It seems to be a non Logitech related issue:
image

**Comment by stefanahman** [comment]
@juliancheal Merge? The build were failing before: https://travis-ci.org/hybridgroup/artoo-joystick/builds

**Comment by stefanahman** [comment]
Due to dead repo

**Pull request closed without merging**
