### PR TITLE
Xbox 360 Controller OS X and trigger support

### PR DESCRIPTION
**Pull request by mikejford**
I modified the xbox360 driver to add trigger support.  Also, I wasn't sure why the button map and axis numbers were set to the wrong values with the original code compared to the values I saw in testing.  I'm assuming this was due to a difference in USB driver support, so I created a separate map for my USB driver and used the additional_params from the Artoo::Driver class to access it.  I kept the original button and axis numbers in the default map.

I added information about the third-party USB driver to the readme as well as details about the trigger support.

### CODE REVIEW

**Comment by mikejford** [comment]
I've also added currently_pressed? command and button_up events.  This allows users of the joystick adaptor to get button values without producing the warning log message about unknown command.  It also allows the users to perform actions when a button is released, such as turning off an LED, without polling on the currently_pressed? values.

**Comment by deadprogram** [comment]
@edgarSilva or @adzankich can you please look at this?

**Comment by edgarsilva** [comment]
Nice, reviewing this.

**Comment by deadprogram** [comment]
Seems like this should be separate driver

**Comment by mikejford** [comment]
Does it make sense to have distinct OS X and Linux drivers for each controller type?

**Comment by deadprogram** [comment]
Make sense? Probably not. However, if the software needed to achieve it requires so much conditional code, we just have to work with the OS-specific ugly, unless I am reading this wrong. What do you all think?

**Comment by mikejford** [comment]
Currently, the only OS conditional code is the get_map method in the xbox360 driver (and ultimately the ps3 driver as well) and the mapping hashes per each supported OS.  I agree that the hashes are a bit ugly.  Perhaps those could get separated into an OS dependent file?

**Comment by mikejford** [comment]
See https://github.com/hybridgroup/artoo-joystick/pull/6 instead.

**Pull request closed without merging**
