### PR TITLE
OS/driver based controller mapping implementation 

### PR DESCRIPTION
**Pull request by mikejford**
Initial refactoring to use os based detection for controller button/axis mappings.

Replaces https://github.com/hybridgroup/artoo-joystick/pull/3

### CODE REVIEW

**Comment by mikejford** [comment]
Just noticed I left my fork of ruby-sdl-ffi in the Gemfile.  Whoops.

**Comment by deadprogram** [comment]
@edgarSilva are you going to review this?

**Comment by edgarsilva** [comment]
Yeap I will review the code, but I do not have a mac or controllers to test this anymore, so I will need someone to help me out and actually test it after reviewing the code.

**Comment by huynguyen** [comment]
I can help test this out for the ps3 controller. Is there anything specific or just button mapping correctness?

**Comment by edgarsilva** [comment]
Just the mapping and basic functionality for the controller. I will review this tomorrow so probably @huynguyen can help out with the testing afterwards, or just do it now make sure it works, and I will review code tomorrow.

**Comment by huynguyen** [comment]
@edgarSilva button mappings are correct in mavericks, with ps3 six axis controller. :+1:

```
System Version: OS X 10.9 (13A603)
Kernel Version: Darwin 13.0.0
```

```
I, [2013-12-15T19:36:19.086210 #30481]  INFO -- : Starting driver 'Artoo::Drivers::Ps3'...
15 => square
12 => triangle
13 => circle
14 => x
10 => l1
8 => l2
11 => r1
9 => r2
0 => select
3 => start
7 => dpad_left
4 => dpad_up
5 => dpad_right
6 => dpad_down
1 => j0
2 => j1
16 => ps3
^CI, [2013-12-15T19:36:45.055219 #30481]  INFO -- : Shutting down...
D, [2013-12-15T19:36:45.057368 #30481] DEBUG -- : Terminating 9 actors...
W, [2013-12-15T19:36:45.059391 #30481]  WARN -- : Terminating task: type=:timer, meta=nil, status=:callwait
```

**Comment by edgarsilva** [comment]
The one that is actually causing issues is the xbox 360 mapping, I was able to get the correct ps3 mapping when I had the mac available, but I was never able to have the xbox 360 working there.

Sorry I should've mentioned that before, if you have the hardware and could give us a hand testing it, it would be awesome.

**Comment by mikejford** [comment]
@huynguyen Take note that OS X doesn't have native support for XBox 360 controller.  I've been using one that I included a link for in the README.md file change.

**Comment by huynguyen** [comment]
I think I can get a hold of one from the office, but might take a bit because of the holidays.

**Comment by stewart** [comment]
Tested with my 360 controller on Mavericks, all seems good. :shipit:

**Pull request merged**
